name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  push:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint

  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: npm test -- --watchAll=false

  build:
    name: Build Frontend
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run test in build job
        working-directory: starter/frontend
        run: npm test -- --watchAll=false

      - name: Build frontend image using docker
        working-directory: starter/frontend
        run: docker build -t movie-frontend:latest .
